# Generated by Django 3.1.1 on 2020-09-14 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200913_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookForInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.author')),
            ],
        ),
    ]
