# Generated by Django 3.1.1 on 2020-09-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.blog')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('models.blog',),
        ),
    ]
