# Generated by Django 3.1.1 on 2020-09-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20200919_1406'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='author',
            index_together={('name', 'email'), ('email',)},
        ),
    ]
