# Generated by Django 3.1.1 on 2020-09-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_baseproduct_image_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='base_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_product',
        ),
        migrations.DeleteModel(
            name='BaseProduct',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
