# Generated by Django 3.1.1 on 2020-09-30 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20200930_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
