# Generated by Django 3.1.1 on 2020-10-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
